const movieData =
    [
        {
            id: "lightyear",
            title: "Lightyear",
            year: "2022",
            rating: "PG",
            image: "https://www.criticsinc.com/photos/movieposters/l/lightyear.jpg",
            duration: "1h 45m",
            sex_and_nudity: 1,
            sex_and_nudity_text: "Two women kiss and we read a sign celebrating their 40th wedding anniversary. A woman talks about being engaged and that she met her partner while marooned on an alien planet. We see a married pregnant woman.",
            violence_and_gore: 3,
            violence_and_gore_text: "Many large robots stand around a laser shield surrounding an encampment with people inside, and shoot at it. A giant robot punches through a wall and grabs a man on the other side; he holds him off the ground as the man struggles to get free and a young woman shoots at the robot (it turns out to be a training weapon that shoots paint) while a man shoots a harpoon gun at the robot and a woman says that she is not allowed to use weapons because it would violate her parole. A giant robot shoots at people and does not hit them but causes property damage when things (like a satellite dish) are cut in half with laser blasts; the robot is struck in the head with a harpoon and falls hard on the ground motionless (it revives later). A man is chased by a giant robot in several scenes, it slams through passages to get to him and then points a weapon at him but does not fire, and the giant robot is shot by someone else and falls to the ground. A young woman jumps out of a ship and floats through space toward another ship, she misses the entry port and scrambles to grab something to hold onto, and a cat that was with her floats away until the young woman grabs it by the tail",
            language: 1,
            language_text: "Name-calling (feisty, oddities, strange, turnip, sad eyes, zurg, lucky, quitter, saucy fingers), exclamations (blast, oh no, you’re toast, I’m gonna mess you up)",
            description: "The origin story of the Buzz Lightyear toy in “Toy Story” follows the Space Rangers as they get marooned on an alien planet. Buzz (voiced by Chris Evans) is determined to get everyone back home and complete their mission, while encountering an army of ruthless robots led by the evil Zurg (voiced by James Brolin). Also with the voices of Keke Palmer, Peter Sohn, Taika Waititi, Dale Soules, Uzo Aduba, Mary McDonald-Lewis, Isiah Whitlock Jr., Angus MacLane and Bill Hader. Directed by Angus MacLane",
        },        {
            id: "avatar",
            title: "Avatar: The Way of Water",
            year: "2022",
            rating: "PG",
            image: "https://media-cache.cinematerial.com/p/500x/gvbzokwl/black-panther-wakanda-forever-movie-poster.jpg?v=1664882491",
            duration: "1h 45m",
            sex_and_nudity: 1,
            sex_and_nudity_text: "Two women kiss and we read a sign celebrating their 40th wedding anniversary. A woman talks about being engaged and that she met her partner while marooned on an alien planet. We see a married pregnant woman.",
            violence_and_gore: 3,
            violence_and_gore_text: "Many large robots stand around a laser shield surrounding an encampment with people inside, and shoot at it. A giant robot punches through a wall and grabs a man on the other side; he holds him off the ground as the man struggles to get free and a young woman shoots at the robot (it turns out to be a training weapon that shoots paint) while a man shoots a harpoon gun at the robot and a woman says that she is not allowed to use weapons because it would violate her parole. A giant robot shoots at people and does not hit them but causes property damage when things (like a satellite dish) are cut in half with laser blasts; the robot is struck in the head with a harpoon and falls hard on the ground motionless (it revives later). A man is chased by a giant robot in several scenes, it slams through passages to get to him and then points a weapon at him but does not fire, and the giant robot is shot by someone else and falls to the ground. A young woman jumps out of a ship and floats through space toward another ship, she misses the entry port and scrambles to grab something to hold onto, and a cat that was with her floats away until the young woman grabs it by the tail",
            language: 1,
            language_text: "Name-calling (feisty, oddities, strange, turnip, sad eyes, zurg, lucky, quitter, saucy fingers), exclamations (blast, oh no, you’re toast, I’m gonna mess you up)",
            description: "The origin story of the Buzz Lightyear toy in “Toy Story” follows the Space Rangers as they get marooned on an alien planet. Buzz (voiced by Chris Evans) is determined to get everyone back home and complete their mission, while encountering an army of ruthless robots led by the evil Zurg (voiced by James Brolin). Also with the voices of Keke Palmer, Peter Sohn, Taika Waititi, Dale Soules, Uzo Aduba, Mary McDonald-Lewis, Isiah Whitlock Jr., Angus MacLane and Bill Hader. Directed by Angus MacLane",
        },        {
            id: "lightyear",
            title: "Lightyear",
            year: "2022",
            rating: "PG",
            image: "https://cdn.cinematerial.com/p/297x/fbn7nr8g/the-menu-movie-poster-md.jpg?v=1663164571",
            duration: "1h 45m",
            sex_and_nudity: 1,
            sex_and_nudity_text: "Two women kiss and we read a sign celebrating their 40th wedding anniversary. A woman talks about being engaged and that she met her partner while marooned on an alien planet. We see a married pregnant woman.",
            violence_and_gore: 3,
            violence_and_gore_text: "Many large robots stand around a laser shield surrounding an encampment with people inside, and shoot at it. A giant robot punches through a wall and grabs a man on the other side; he holds him off the ground as the man struggles to get free and a young woman shoots at the robot (it turns out to be a training weapon that shoots paint) while a man shoots a harpoon gun at the robot and a woman says that she is not allowed to use weapons because it would violate her parole. A giant robot shoots at people and does not hit them but causes property damage when things (like a satellite dish) are cut in half with laser blasts; the robot is struck in the head with a harpoon and falls hard on the ground motionless (it revives later). A man is chased by a giant robot in several scenes, it slams through passages to get to him and then points a weapon at him but does not fire, and the giant robot is shot by someone else and falls to the ground. A young woman jumps out of a ship and floats through space toward another ship, she misses the entry port and scrambles to grab something to hold onto, and a cat that was with her floats away until the young woman grabs it by the tail",
            language: 1,
            language_text: "Name-calling (feisty, oddities, strange, turnip, sad eyes, zurg, lucky, quitter, saucy fingers), exclamations (blast, oh no, you’re toast, I’m gonna mess you up)",
            description: "The origin story of the Buzz Lightyear toy in “Toy Story” follows the Space Rangers as they get marooned on an alien planet. Buzz (voiced by Chris Evans) is determined to get everyone back home and complete their mission, while encountering an army of ruthless robots led by the evil Zurg (voiced by James Brolin). Also with the voices of Keke Palmer, Peter Sohn, Taika Waititi, Dale Soules, Uzo Aduba, Mary McDonald-Lewis, Isiah Whitlock Jr., Angus MacLane and Bill Hader. Directed by Angus MacLane",
        },        {
            id: "lightyear",
            title: "Lightyear",
            year: "2022",
            rating: "PG",
            image: "https://media-cache.cinematerial.com/p/500x/njdjtd4d/violent-night-movie-poster.jpg?v=1663170344",
            duration: "1h 45m",
            sex_and_nudity: 1,
            sex_and_nudity_text: "Two women kiss and we read a sign celebrating their 40th wedding anniversary. A woman talks about being engaged and that she met her partner while marooned on an alien planet. We see a married pregnant woman.",
            violence_and_gore: 3,
            violence_and_gore_text: "Many large robots stand around a laser shield surrounding an encampment with people inside, and shoot at it. A giant robot punches through a wall and grabs a man on the other side; he holds him off the ground as the man struggles to get free and a young woman shoots at the robot (it turns out to be a training weapon that shoots paint) while a man shoots a harpoon gun at the robot and a woman says that she is not allowed to use weapons because it would violate her parole. A giant robot shoots at people and does not hit them but causes property damage when things (like a satellite dish) are cut in half with laser blasts; the robot is struck in the head with a harpoon and falls hard on the ground motionless (it revives later). A man is chased by a giant robot in several scenes, it slams through passages to get to him and then points a weapon at him but does not fire, and the giant robot is shot by someone else and falls to the ground. A young woman jumps out of a ship and floats through space toward another ship, she misses the entry port and scrambles to grab something to hold onto, and a cat that was with her floats away until the young woman grabs it by the tail",
            language: 1,
            language_text: "Name-calling (feisty, oddities, strange, turnip, sad eyes, zurg, lucky, quitter, saucy fingers), exclamations (blast, oh no, you’re toast, I’m gonna mess you up)",
            description: "The origin story of the Buzz Lightyear toy in “Toy Story” follows the Space Rangers as they get marooned on an alien planet. Buzz (voiced by Chris Evans) is determined to get everyone back home and complete their mission, while encountering an army of ruthless robots led by the evil Zurg (voiced by James Brolin). Also with the voices of Keke Palmer, Peter Sohn, Taika Waititi, Dale Soules, Uzo Aduba, Mary McDonald-Lewis, Isiah Whitlock Jr., Angus MacLane and Bill Hader. Directed by Angus MacLane",
        },        {
            id: "lightyear",
            title: "Lightyear",
            year: "2022",
            rating: "PG",
            image: "https://cdn.cinematerial.com/p/297x/8typ50xo/strange-world-movie-poster-md.jpg?v=1666243728",
            duration: "1h 45m",
            sex_and_nudity: 1,
            sex_and_nudity_text: "Two women kiss and we read a sign celebrating their 40th wedding anniversary. A woman talks about being engaged and that she met her partner while marooned on an alien planet. We see a married pregnant woman.",
            violence_and_gore: 3,
            violence_and_gore_text: "Many large robots stand around a laser shield surrounding an encampment with people inside, and shoot at it. A giant robot punches through a wall and grabs a man on the other side; he holds him off the ground as the man struggles to get free and a young woman shoots at the robot (it turns out to be a training weapon that shoots paint) while a man shoots a harpoon gun at the robot and a woman says that she is not allowed to use weapons because it would violate her parole. A giant robot shoots at people and does not hit them but causes property damage when things (like a satellite dish) are cut in half with laser blasts; the robot is struck in the head with a harpoon and falls hard on the ground motionless (it revives later). A man is chased by a giant robot in several scenes, it slams through passages to get to him and then points a weapon at him but does not fire, and the giant robot is shot by someone else and falls to the ground. A young woman jumps out of a ship and floats through space toward another ship, she misses the entry port and scrambles to grab something to hold onto, and a cat that was with her floats away until the young woman grabs it by the tail",
            language: 1,
            language_text: "Name-calling (feisty, oddities, strange, turnip, sad eyes, zurg, lucky, quitter, saucy fingers), exclamations (blast, oh no, you’re toast, I’m gonna mess you up)",
            description: "The origin story of the Buzz Lightyear toy in “Toy Story” follows the Space Rangers as they get marooned on an alien planet. Buzz (voiced by Chris Evans) is determined to get everyone back home and complete their mission, while encountering an army of ruthless robots led by the evil Zurg (voiced by James Brolin). Also with the voices of Keke Palmer, Peter Sohn, Taika Waititi, Dale Soules, Uzo Aduba, Mary McDonald-Lewis, Isiah Whitlock Jr., Angus MacLane and Bill Hader. Directed by Angus MacLane",
        },
    ]



export default movieData;